import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex items-center justify-center bg-gray-900 px-4">
          <div className="p-6 max-w-sm w-full bg-gray-800 rounded-lg border border-gray-700 shadow-md">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
